# Generated by Django 5.2.10 on 2026-01-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validating_airline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Продавец (Валидирующая компания)')),
                ('ticket_uid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Идентификатор билета (из HTML)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('route_type', models.CharField(choices=[('one_way', 'One-Way'), ('round_trip', 'Roundtrip'), ('multi_city', 'Multi-City')], max_length=20, verbose_name='Тип маршрута')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['ticket_uid'],
            },
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_airline', models.CharField(max_length=100, verbose_name='Фактический перевозчик')),
                ('departure', models.CharField(max_length=10, verbose_name='Аэропорт вылета')),
                ('departure_date', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival', models.CharField(max_length=10, verbose_name='Аэропорт прилета')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок сегмента')),
                ('ticket', models.ForeignKey(db_column='ticket_uid', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='flights.ticket', to_field='ticket_uid', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Сегмент перелета',
                'verbose_name_plural': 'Сегменты перелета',
                'ordering': ['ticket', 'order'],
            },
        ),
    ]
