# Generated by Django 5.2.10 on 2026-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=10, verbose_name='Аэропорт вылета')),
                ('destination', models.CharField(max_length=10, verbose_name='Аэропорт прилета')),
                ('departure_date', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время прилета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('airline', models.CharField(max_length=100, verbose_name='Авиакомпания')),
                ('route_type', models.CharField(choices=[('one-way', 'One Way'), ('round-trip', 'Round Trip'), ('multi-city', 'Multi City')], default='one-way', max_length=20, verbose_name='Тип рейса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination', 'departure_date', 'airline', 'price'), name='unique_flight_catch')],
            },
        ),
    ]
